---
engines:
  duplication:
    enabled: true
    config:
      languages:
        - ruby
    exclude_paths:
      - 'test/**/*'
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
    - "**.rb"
checks:
  method-complexity:
    config:
      threshold: 10
exclude_paths:
  - vendor/bundle
  - .idea
  - bin

